# Generated by Django 4.2.8 on 2024-01-05 14:42

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='images/no_avatar.png', upload_to=account.models.avatar_url),
        ),
    ]
