# Generated by Django 4.2.8 on 2024-01-11 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_alter_post_attending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attending',
        ),
        migrations.AddField(
            model_name='post',
            name='attending',
            field=models.ManyToManyField(default=None, related_name='attend_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
