# Generated by Django 4.2.8 on 2024-01-13 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_attending_post_attending'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attend',
        ),
    ]
