# Generated by Django 4.2.8 on 2024-01-19 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_delete_attend'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
