# Generated by Django 4.2.8 on 2024-01-19 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
